### ISSUE TITLE
Wrong Adress on Ledger Nano S with Advanced Passphrase

### ISSUE THREAD

**Issue by Delte** [binance-chain/ledger-app-binance#7]
When i connect with my ledger device my testnet address on device same as shown on my account, but when i activate 25. word passphrase account with pin on my ledger testnet address is different with dex account shown one.

Reproduce: 
1. Plug Ledger nano s 
2. Unlock with pin 
3. Open Settings Menu 
4. Enter Security sub-menu 
5. Select Passphrase 
6. Choose Attach to a PIN option from the Passphrase menu in the device security settings. 
7. Create a secondary PIN code. 
8. Re-enter the secondary PIN code to confirm it. 
9. Choose and confirm a secret passphrase (max 100 characters) 
10. Enter your primary PIN code to validate. 
11. Turn off the device and enter your secondary PIN code to access the passphrase-protected accounts. 
12. Open Binance Chain App on Ledger nano s device 
13. Enter Binance.Dex 
14. Activate wallet with ledger nano s device 
15. Open your address on ledger nano s device 
16. Select testnet 
17. Click Account Photo on Binance.Dex 
18. Compare address on Ledger nano s device with Binance.Dex

Device Firmware : 1.5.5
Binance Chain App version: 1.0.0

Binance Support ticket number: 1303526
its include video

**Comment by notatestuser** [comment]
Thank you, this is a known issue with the old build. We are waiting for a new deployment to Ledger Live to update the address display.

**Comment by notatestuser** [comment]
Fixed in v1.0.2
